variables:
  GIT_STRATEGY: clone

stages:
  - test
  - deploy

deploy_dev:
  stage: deploy
  only:
    - develop
  tags:
    - etl-dev
  script:
    - echo "Deploy to etl-dev server"
    - pwd
    - whoami
    - rsync -ah --stats * /home/onenet/on-vds-dmp-etl --delete
