// FACT_ACCOUNT
CREATE TABLE IF NOT EXISTS `fact_account`
(
    `account_id` bigint NOT NULL,
    `user_id` bigint,
    `msisdn` varchar(255),
    `account_state_id` int,
    `account_type_id` int,
    `account_balance` float,
    `account_holding_balance` float,
    `account_available_balance` float,
    `currency_id` int,
    `created_date` datetime,
    `modified_date` datetime,
    `last_change_balance` datetime,
    `last_trans_time` datetime,
    `active_time` datetime,
    `is_master_account` int,
    `account_tier` int,
    `inviter_account` bigint,
    `wh_etl_session_key` int,
    `wh_load_ts_unix` bigint,
    `wh_source_data` varchar(255)
)

// FACT_TRANSACTION
CREATE TABLE IF NOT EXISTS `fact_transaction`
(
    `transaction_id` bigint NOT NULL,
    `from_account` bigint,
    `from_phone` varchar(255),
    `from_name` varchar(255),
    `from_party_role` bigint,
    `to_account` bigint,
    `to_phone` varchar(255),
    `to_name` varchar(255),
    `to_party_role` bigint,
    `carried_account` bigint,
    `carried_name` varchar(255),
    `carried_phone` varchar(255),
    `carried_code` varchar(255),
    `reason_id` int,
    `app_channel_id` int,
    `transaction_state_id` int,
    `transaction_type_id` int,
    `currency_id` int,
    `amount` float,
    `discount` float,
    `fee` float,
    `commission` float,
    `total_amount` float,
    `revenue_shared` float,
    `partner_code` varchar(255),
    `service_code` varchar(255),
    `date_created` datetime,
    `date_created_key` int,
    `date_modified` datetime,
    `date_expired` datetime,
    `date_deadline` datetime,
    `date_finished` datetime,
    `start_request_time` datetime,
    `end_response_time` datetime,
    `avg_process_time` int,
    `number_steps` int,
    `sum_step_process_time` float,
    `avg_step_process_time` float,
    `wh_etl_session_key` int,
    `wh_load_ts_unix` bigint,
    `wh_source_data` varchar(255)
)