WITH request AS (
SELECT
    CAST(refund_request.transaction_id AS bigint) AS transaction_id,
    transfer_order.sender_wallet_id AS from_account,
    NULL AS from_phone,
    transfer_order.sender_name AS from_name,
    transfer_order.sender_role_id AS from_party_role,
    transfer_order.receiver_wallet_id AS to_account,
    transfer_order.receiver_tel AS to_phone,
    transfer_order.receiver_name AS to_name,
    transfer_order.receiver_role_id AS to_party_role,
    transfer_order.carrier_wallet_id AS carried_account,
    NULL AS carried_name,
    transfer_order.carrier_tel AS carried_phone,
    NULL AS carried_code,
    NULL AS reason_id,
    NULL AS app_channel_id,
    NULL AS transaction_state_id,
    NULL AS transaction_type_id,
    NULL AS currency_id,
    transfer_order.amount,
    transfer_order.fee,
    transfer_order.discount,
    transfer_order.commission,
    (transfer_order.amount + transfer_order.fee - transfer_order.discount) AS total_amount,
    transfer_order.revenue_shared,
    transfer_order.partner_code,
    transfer_order.service_code,
    transfer_order.created_at AS date_created,
    transfer_order.created_at AS date_created_key,
    transfer_order.updated_at AS date_modified,
    NULL AS date_expired,
    NULL AS date_deadline,
    NULL AS date_finished,
    NULL AS start_request_time,
    NULL AS end_response_time,
    NULL AS avg_process_time,
    NULL AS num_steps,
    NULL AS sum_step_process_time,
    NULL AS avg_step_process_time,
    NULL AS wh_etl_session_key,
    CURRENT_TIMESTAMP() AS wh_load_ts_unix,
    NULL AS wh_source_data
FROM w3_transfer_business.transfer_order transfer_order
LEFT JOIN w3_transfer_business.refund_request refund_request ON transfer_order.id = refund_request.transfer_order_id
UNION
SELECT
    CAST(transaction_id AS bigint) AS transaction_id,
    from_wallet_id AS from_account,
    NULL AS from_phone,
    NULL AS from_name,
    from_role_id AS from_party_role,
    to_wallet_id AS to_account,
    NULL AS to_phone,
    NULL AS to_name,
    to_role_id AS to_party_role,
    NULL AS carried_account,
    NULL AS carried_name,
    NULL AS carried_phone,
    NULL AS carried_code,
    NULL AS reason_id,
    NULL AS app_channel_id,
    NULL AS transaction_state_id,
    NULL AS transaction_type_id,
    NULL AS currency_id,
    NULL AS amount,
    NULL AS fee,
    NULL AS discount,
    NULL AS commission,
    NULL AS total_amount,
    NULL AS revenue_shared,
    partner_code,
    service_code,
    created_at AS date_created,
    created_at AS date_created_key,
    updated_at AS date_modified,
    NULL AS date_expired,
    NULL AS date_deadline,
    NULL AS date_finished,
    NULL AS start_request_time,
    NULL AS end_response_time,
    NULL AS avg_process_time,
    NULL AS num_steps,
    NULL AS sum_step_process_time,
    NULL AS avg_step_process_time,
    NULL AS wh_etl_session_key,
    CURRENT_TIMESTAMP() AS wh_load_ts_unix,
    NULL AS wh_source_data
FROM w3_transfer_business.stock_request
)
SELECT
    request.transaction_id,
    request.from_account,
    request.from_phone,
    request.from_name,
    request.from_party_role,
    request.to_account,
    request.to_phone,
    request.to_name,
    request.to_party_role,
    request.carried_account,
    request.carried_name,
    request.carried_phone,
    request.carried_code,
    request.reason_id,
    client_request.access_channel AS app_channel_id,
    transaction_utility.transaction_state AS transaction_state_id,
    transaction_utility.trans_type AS transaction_type_id,
    transaction_utility.currency_code AS currency_id,
    transaction_utility.amount,
    transaction_utility.fee,
    transaction_utility.discount,
    transaction_utility.commission,
    (transaction_utility.amount + transaction_utility.fee - transaction_utility.discount) AS total_amount,
    transaction_utility.revenue_shared,
    transaction_utility.partner_code,
    transaction_utility.service_code,
    transaction_utility.created_date AS date_created,
    transaction_utility.created_date AS date_created_key,
    transaction_utility.modified_date AS date_modified,
    NULL AS date_expired,
    NULL AS date_deadline,
    NULL AS date_finished,
    NULL AS start_request_time,
    NULL AS end_response_time,
    NULL AS avg_process_time,
    NULL AS num_steps,
    NULL AS sum_step_process_time,
    NULL AS avg_step_process_time,
    NULL AS wh_etl_session_key,
    CURRENT_TIMESTAMP() AS wh_load_ts_unix,
    NULL AS wh_source_data
FROM request
JOIN transaction_utility ON request.transaction_id = transaction_utility.transaction_id
JOIN request_detail ON transaction_utility.request_detail_id = request_detail.request_detail_id
JOIN client_request ON request_detail.client_request_id = client_request.client_request_id