SELECT 
    id
    ,first_name
    ,last_name
    ,username
    ,email
    ,phone_number
    ,birthday
    ,country
    ,image_url
    ,status
    ,lang
    ,sex
    ,time_zone
    ,reset_date
    ,reset_key
    ,activation_key
    ,created_at
    ,created_by
    ,updated_at
    ,updated_by
    ,deleted_at
    ,deleted_by
FROM w3_core_uaa_datawarehouse.users