name: Pull ETL
on:
  push:
    branches:
      - develop

jobs:
  auto-pull:
    name: pull_develop
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: develop
    - name: Pull origin
      run: git pull origin develop